### PR TITLE
Zoom days in week, fix #65

### LINKED ISSUE #65: Week view: display more than three days
To get an better overview and being really useful, the week view should be able to display more than only three days at once.

### PR DESCRIPTION
**Pull request by hummlbach**
Remarks:
- Should also be tested on slower devices. On my meizu pro 5(!) wild zooming has hiccups. While this does not happen on my laptop. I'm not sure how to improve this, but since it is thought to be used only occasionally and in an non-wild-manner, it's perhaps okay(?)
- zoom is not done around center - does someone mind that? :) Sure - it would be nicer if the zoom center would be respected...
- scrolling to next week does not work properly, if fully zoomed out (didn't get why yet), so the zoom out is restricted to 7 days minus epsilon

### CODE REVIEW

**Comment by sverzegnassi** [comment]
Seems a nice addition, well done!

> Should also be tested on slower devices. [...]

Atm I can't test it on a low-end device. @NeoTheThird or @Flohack74, could you? 

> zoom is not done around center - does someone mind that? [...]
I haven't even noticed. :) Anyway, being a secondary feature, I don't believe it should be a priority for now

> scrolling to next week does not work properly, if fully zoomed out (didn't get why yet), so the zoom out is restricted to 7 days minus epsilon

Should we consider this as a blocker?

**Comment by NeoTheThird** [comment]
Good job!

The FP2 is the slowest device I have at the moment, maybe @Flohack74 could test on the E4.5 to make sure the lag's not too bad. Else than that i think we can merge!

We should probably fix the deb build at some point...

**Comment by Flohack74** [comment]
Ok will do a test run on my GFs phone xD

**Comment by NeoTheThird** [comment]
Any news @Flohack74?

**Comment by Flohack74** [comment]
Uh missed that one. Well need a click to test, let me try to build it.

**Comment by hummlbach** [comment]
That https://github.com/ubports/calendar-app/releases/tag/v0.7.0-beta2 would have been the corresponding release ;)

**Comment by NeoTheThird** [comment]
*pokes @Flohack74 *

**Comment by hummlbach** [comment]
Has been tested by @timsueberkrueb on an bq e4.5. Should be fine... Please merge #68

**Pull request closed without merging**
