### PR TITLE
Issue67 zoom hours

### PR DESCRIPTION
**Pull request by hummlbach**

### CODE REVIEW

**Comment by hummlbach** [comment]
Uhh, scrolling today is problematic a.t.m. the red line (showing current time) gets screwed up... Has to be fixed.

**Comment by hummlbach** [comment]
From my side this branch is now ready for merging. There are no known issues anymore. So: call for (hopefully) final testing.

**Comment by hummlbach** [comment]
I've tested it on my laptop, the meizu pro 5 and now also on the nexus 4 with _16.04_ woho! :)
On the nexus 4, it strikes that the model is updated after zooming (since there it causes the blue turning circle to appear for a short time). I'll change that.

**Comment by hummlbach** [comment]
My plan was to have the version 0.7.0 when the zooming stuff is merged in. The general idea would have been to bump the patch number for bug fixes and features that acquire only small local changes and bumping minor for entirely new features with bigger changes.

**Comment by NeoTheThird** [comment]
Ok, do you maybe want to rebase so only the stuff you want in there is included?

**Comment by hummlbach** [comment]
@NeoTheThird should be fine. As @Flohack74 suggested (you [plural] would bump the version number) I reverted the version number.

**Comment by Flohack74** [comment]
So when I merge this, you will take care of the other PRs, and sort out if they are no longer needed?

**Comment by hummlbach** [comment]
Of course :)

**Pull request merged**
