### PR TITLE
Sections in header instead of menu

### PR DESCRIPTION
**Pull request by krille-chan**

### CODE REVIEW

**Comment by ChristianPauly** [comment]
There are two proposals. This are the normal "Sections" from the Ubuntu Components:
ppzflschklvxmtssmxewvqwr
The problem with this is, that the user may think that he can swipe to the left or the right to switch between these sections but he will just switch the month, the week and so on...

krwwzfppfxmtpuasjazkcoje
Does not have this problem but it may not look so nice...

**Comment by hummlbach** [comment]
I didn't know that the normal/usual way to change the tabs is by swiping left or right :) at least in podbird and the address-book-app thats not the case. Thanks for creating that!

**Comment by ChristianPauly** [comment]
> I didn't know that the normal/usual way to change the tabs is by swiping left or right :) at least in podbird and the address-book-app thats not the case. Thanks for creating that!

Ooh, I see you are right 😅 well maybe I was wrong about this assumption.

**Comment by UniversalSuperBox** [comment]
It *is* how you switch tabs in clock-app though. If we think this is something we want to do, we would need to implement it across all the core apps with tabbed UI.

**Comment by bhdouglass** [comment]
@hummlbach is this something we want to merge in? Might want @cibersheep to check it out.

**Comment by cibersheep** [comment]
I vote for the first option (with the tabs). The only app that changes tabs with a swipe is the clock, which is not the default behaviour of tabs :)

I love that you take away the left menu hurray!

imatge

**Comment by hummlbach** [comment]
> @hummlbach is this something we want to merge in?

Yes, we definitely want to have that! I've already discussed with @ChristianPauly 3 weeks ago. As @cibersheep I would opt for the first. We were also discussing about the order of the tabs. Here i would like to reverse the order. @ChristianPauly either you do it, or I'll do that next week and afterwards lets merge it.
One additional thing; actually there are more severe glitches with the calendar on a big screen, but nonetheless: any idea how to make that look better? (Or is it okay with the tabs left aligned, looks a bit strange to me....)
calendarsections

**Comment by ChristianPauly** [comment]
I would place the tabs in the center. That makes the best look on large screens or on the desktop. Or maybe even better we place them in the center and put them in the top header between the "January 2018" and the three buttons on the right, when the application window is large enaugh for it.

**Comment by ChristianPauly** [comment]
What do you think about this solution? When the window is large enaugh, the header will have only one row and the sections will be centered:
https://chat.regionetz.net/_matrix/media/v1/download/chat.regionetz.net/vhdcIAxzOwjUpqcciVvfoyGx

And it is changing automatically from the two states as you can see here:
https://janian.de/index.php/s/CpfDpZe2nLCCnf3

**Review by hummlbach — CHANGES_REQUESTED** [review]
Here is my suggestion, on how to change the tab order.
[change_tab_order.patch.txt](https://github.com/ubports/calendar-app/files/2923741/change_tab_order.patch.txt)

**Comment by cibersheep** [comment]
Looks great to me

**Review by hummlbach — APPROVED** [review]

**Pull request merged**
