### PR TITLE
Update from Weblate.

### PR DESCRIPTION
**Pull request by ubports-weblate**

### CODE REVIEW

**Comment by mardy** [comment]
@Flohack74 for this one, let's please try to accumulate a few merge proposals and then I'll merge them manually in a single commit. I want to see what problems arise, and if we can find a better solution.

**Comment by Flohack74** [comment]
No please dont. I can explain you why it wont work: Weblate is always pushing to a single branch here: https://github.com/ubports-weblate/calendar-app and from there makes the PRs.
When you squash here, you are actually rewriting history, and then Weblate would need to check out the branch as new. Since it does not do this, upon next push it will conflict.
Also it cannot rebase, since it will always try to apply all changes again.
Trust me, we have been through this for months, where I was manually fixing tons of conflictgs just for the sake of having a squash.
The manual option they suggest is to actually put a git reset somehwere (where?) and then apply it as a rebase. This needs to be scripted manually though, so be my guest ;)

**Comment by mardy** [comment]
I see. Well, please give me a couple of days to try it out, and then I'll give up forever :-)

**Comment by Flohack74** [comment]
LOL now Weblate pulled inside stuff from a merge. This is insane...

**Comment by bhdouglass** [comment]
@Flohack74 what's the hold up for merging this?

**Comment by Flohack74** [comment]
As you can see Weblate has committed also non-translation stuff, and I have no clue hbow it happened. It probably replays commits from another PR? I really have no cluea, thats why I left it open.

**Comment by bhdouglass** [comment]
Ok, can you or @hummlbach take a look at this and see if we can't resolve it?

**Comment by Flohack74** [comment]
Now it looks good!

**Pull request merged**
