### PR TITLE
Update policy version and framework

### PR DESCRIPTION
**Pull request by UniversalSuperBox**

### CODE REVIEW

**Comment by hummlbach** [comment]
Is this intended to go to master? Will there be a vivid branch? Or do we stop building it for vivid?

**Comment by UniversalSuperBox** [comment]
The intention is for this to go to master. If you'd like, we could take a vivid branch at this point.

**Comment by hummlbach** [comment]
Just asking. If we don't need to build it for vivid anymore, theres no need for having a vivid branch...

**Comment by Flohack74** [comment]
The vivid branch shall stay also for historical reasons. Maybe someone wants to look up smth later...

**Comment by NeoTheThird** [comment]
The correct thing to use for that would be a tag.

**Comment by Flohack74** [comment]
Ok I am coming from SVN, there its no difference. Yes, a tag is fine. But lets do this later on.

**Pull request merged**
