### PR TITLE
Issue 81: make times respecting the locale

### PR DESCRIPTION
**Pull request by hummlbach**
- format the times displayed in the time line column according to the locale
- added item/label template to calendar.qml to calculate time scale column
  width depending on the time label (which itself depends on the locale now)
- Changed CustomPickers HoursModel to respect the locale

click for testing (16.04): https://github.com/hummlbach/calendar-app/releases/download/v0.7.2-beta4/com.ubuntu.calendar_0.7.2-beta4_armhf.click

### CODE REVIEW

**Comment by bhdouglass** [comment]
@hummlbach this is looking great! One thing I did notice was in the time picker when creating a new event. It shows 12 hour time, but it doesn't show am/pm so there are two 1s but the user doesn't know if that's 1am or 1pm.

**Comment by hummlbach** [comment]
@bhdouglass yes i agree, thats suboptimal. But as it is implemented with this PR, there's no need for a distinction by cases/locales. (I assume we all agree that it would not be a good thing...) Unfortunately with my limited qml knowledges i don't have a good idea how to add the am/pm in the date picker (without explicity checking for the locale) thats a bit tricky... and this date picker components are damn complex... :) Having the AM/PM in front of the hour on the first wheel would be easy, but also very ugly... actually we would need three wheels instead of two: the first only having numbers from 1 to 12 and the third wheel only having AM and PM on it... so i think the solution would be: take a date, foramt it as string according to the locale and transform that somehow into either "hh:mm" or "hh:mm ap" or something (which is used as input for the picker) and implement a new model for picker model for am/pm... so not optimal, but at least you see it "in the background"...

**Comment by bhdouglass** [comment]
@hummlbach since you already know whether or not it's am/pm (it's being displayed in the field that you click on), would it be possible to have a static 3rd column that just shows am/pm (but not selectable)? My concern with this is that people I know would be frustrated with the current implementation, so it would be a smoother experience to get this correct. As it stands it's ok by me, but I'm more tolerant of these little issues, not every user will be.

**Comment by hummlbach** [comment]
I totally agree am/pm should be displayed by the picker. But I'm not willing to invest the time now. But I can well imagine doing it later. Would mostly be an extension to the changes in the PR. So I suggest merging this and open an issue for am/pm not being displayed in the picker.

**Pull request merged**
