### PR TITLE
Issue6 recurrence interval

### PR DESCRIPTION
**Pull request by hummlbach**
Mhmm... i did something wrong... actually i wanted to request the merge of a single commit only... Not the bump of the version number...
A click package for testing can be found here: https://github.com/ubports/calendar-app/releases/tag/v0.7.1

### CODE REVIEW

**Comment by Flohack74** [comment]
@hummlbach I am not sure I understand your branching model :)
grafik

Basically this tells me that if we merge issue11, also all changes for issue65 and 67 are thrown in. If you want to work in an atomic style, your issue branches must always start at master, not at a previous issue branch...

**Comment by hummlbach** [comment]
Since the 'fix' for issue #67 also relies on the component introduced and changes made for issue #65, I've decided to 'continue' the issue #65 branch. I agree that I should have branched from master for issue #11. I did so for issue #65 (issue #28 branch already existed and not included) and alsoissue for issue #6

**Comment by hummlbach** [comment]
@neothethird I already added a third commit, to correct the version number... The bumping of the version how we do it now is bescheuert, because now the branches have to be merged in the right order. But do not have a better idea. Any suggestions?

**Comment by Flohack74** [comment]
I would suggest to not change version number in feature branches. Only on master, at time of release. Everything else therefore has either the latest version number or an older one. Quite safe ;)

**Comment by Flohack74** [comment]
So also to resolve the conflict here, please take the manifest from master.

**Comment by hummlbach** [comment]
That means either an extra pull request solely for bumping the version number, or you (@neothethird) bump the version number.
And: Which version numbers will the releases on github have then? They would either have the version number of the latest release an the new versions will not be installed without error, or I bump the version number manually and the uploaded click is not 100% consistent with the tag.

**Comment by Flohack74** [comment]
Sooner or later all core APp maintainers should have direct access to the Github repo they maintain. For the moment I propose you leave the version number as it is, and we increase on release. Because it can also create issues with other people wanting to do the same. Tagging and releasing can be covered by us for the moment, if necessary.

**Comment by NeoTheThird** [comment]
Please rebase to resolve the conflict.

**Comment by hummlbach** [comment]
Done. Please approve and merge.

**Comment by Flohack74** [comment]
So merged. If I would be able to get CI to life, we could try to automatically integrate it into the root fs.

**Pull request merged**
