### PR TITLE
Bump version to 0.7.2

### PR DESCRIPTION
**Pull request by hummlbach**
Seems we should really release this quickly: https://github.com/ubports/ubuntu-touch/issues/919

### CODE REVIEW

**Comment by Flohack74** [comment]
Sorry but CI says no... ;)

**Comment by hummlbach** [comment]
As always: https://ci.ubports.com/blue/organizations/jenkins/calendar-app/activity? its only the failing arm64 build isn't it? And that is failing since the sphinx has lost its nose...(?)

**Comment by hummlbach** [comment]
I did, but failed... Changed the label for the armhf build from arm64 to armhf, causing the armhf build to not end anymore??? :(

**Comment by hummlbach** [comment]
I disabled the arm64 build but now its failing at the results stage...

**Comment by hummlbach** [comment]
okay, i guess i need a new PR then...

**Pull request closed without merging**
