### PR TITLE
Lighter colors for calendars

### LINKED ISSUE #148: Some calendar colors are difficult to see on indicator
Aubergine, grey and navy blue are difficult to see in the indicator, I suggest to change them to other similar Suru colors:

grey #888888
purple #77216f
turquoise #006a97

imatge

### PR DESCRIPTION
**Pull request by cibersheep**
Might fix #148

### CODE REVIEW

**Comment by hummlbach** [comment]
Would be cool if you could replace the color picker with another ones instead of some colors in it s.t. #109 would be also fixed...(?) ;-)

**Comment by cibersheep** [comment]
Yep. That would be nice.
Let's see how this behaves first :) as I don't know how the colors are passed to the indicator.

Have you done any try?

**Comment by bhdouglass** [comment]
@hummlbach what's the status of this?

**Comment by cibersheep** [comment]
There's two different issues here. The feature requested has tangencial relation with this fix :)

**Comment by bhdouglass** [comment]
Gotcha, then can we get this merged in?

**Comment by cibersheep** [comment]
I think we might (as it proposes a fix to an specific issue we have now) and keep an eye to the selector idea which I think is very interesting but it will take more time and more skills

**Comment by bhdouglass** [comment]
That makes sense to me, lets fix the issue we have and implement a color picker later. What do you think @hummlbach ?

**Comment by hummlbach** [comment]
In principle I'm fine with the change. two remarks on it:
- for the light theme the text on the events is white, so the colors shouldn't be too light. But the ones you chose are just fine ofc
- if we're changinge the colors in the picker now we could also change the red or the orange, since I can hardly see a difference between them...(?)
Adding some pictures:

**Review by hummlbach — APPROVED** [review]
Would be nice to have the orange and red to be more different. Maybe by making the red more brown(?).

**Comment by bhdouglass** [comment]
@cibersheep are you getting these colors from the ubuntu color pallet?

**Comment by cibersheep** [comment]
@hummlbach I think when we go into a color pick, it could be a «free» color pick, something like Mateo Salta did for Webapp Creator. And be able to choose any color. I don't know if it's feasible though as I don't know if the colors are stored somewhere (between app and indicator).
@bhdouglass I got the colors from the palette and used the ones I changed from the contacts app :)

**Comment by bhdouglass** [comment]
:+1: we should probably stick to the pallet until we add a color picker. Is the one in the webapp creator something that we could reuse here? No sense in reinventing the wheel. (I know that off topic for this PR)

**Comment by cibersheep** [comment]
@bhdouglass so we are safe as I used the colors in the palette.
The webapp creator picker code is something we could use easily, yes.

**Comment by hummlbach** [comment]
Maybe we could make a call for examples for existing color pickers in ut apps... and choose the nicest...(?)

**Comment by bhdouglass** [comment]
@cibersheep sounds good, then it makes sense to me to merge this and investigate reusing the code from the webapp creator.

@hummlbach that's definitely something that could be kicked around in the design channel(s)

**Comment by cibersheep** [comment]
@bhdouglass (I thought I answered this already, but not too many tabs opened :D)
We can reuse the Webapp Creator for sure, what we need also to investigate is how to store the color info (if possible)

**Comment by UniversalSuperBox** [comment]
So... is this approved and ready for merge then? :)

**Review by bhdouglass — APPROVED** [review]

**Comment by bhdouglass** [comment]
Yes this is just pending @hummlbach hitting the merge button.

**Comment by hummlbach** [comment]
Sorry. Done. ^^

**Pull request merged**
